name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install ocaml-nox ocaml-findlib dune menhir texlive-latex-base texlive-pictures texlive-latex-extra
    - name: Build
      run: make test
    - name: Generate website
      run: |
        sudo apt-get -y install pandoc
        make -C website
        cd website && tar zcvf ../github-pages *.html *.css fig/*
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
